source 'https://rubygems.org'

gem 'rake'
gem 'yajl-ruby'
gem 'mimetype-fu'

gem 'static-sprockets', :git => 'git://github.com/jvatic/static-sprockets.git', :branch => 'master'
gem 'rack-putty', :git => 'git://github.com/tent/rack-putty.git', :branch => 'master'
gem 'sprockets', :git => 'git://github.com/rails/sprockets.git', :tag => 'v3.2.0'
gem 'es6-module-mapper', :git => 'https://github.com/jvatic/es6-module-mapper.git', :branch => 'master'
gem 'react-jsx-sprockets', :git => 'https://github.com/jvatic/react-jsx-sprockets', :branch => 'master'
gem 'marbles-js', :git => 'https://github.com/jvatic/marbles-js.git', :branch => 'es6-modules'

gem "flynn-dashboard-web-icons", :git => "git://github.com/flynn/flynn-dashboard-web-icons.git", :branch => "master"
