require 'bundler/setup'

require './config'
require 'static-sprockets/tasks/assets'
require 'static-sprockets/tasks/layout'

namespace :assets do
  task :clean do
    system("rm -rf "+ StaticSprockets.config[:output_dir])
  end
end

task :compile => ["assets:clean", "assets:precompile", "layout:compile"] do
end
