#!/bin/bash
HOSTNAME=localhost
ROOT=/var/lib/demo/apps
SHELF_HOST=localhost:8888

mkdir -p $ROOT

APP="$2"

echo "-----> Building $APP ..."
cat | docker run -i -a stdin -a stdout flynn/slugbuilder http://$SHELF_HOST/slugs/$APP.tgz

echo "-----> Deploying $APP ..."
if [[ ! -f "$ROOT/$APP/PORT" ]]; then
	# First deploy
	id=$(docker run -d -p 5000 -e PORT=5000 -e SLUG_URL=http://$SHELF_HOST/slugs/$APP.tgz flynn/slugrunner start web)
	echo $id > "$ROOT/$APP/CONTAINER"
	port=$(docker port $id 5000)
	echo $port > "$ROOT/$APP/PORT"
	echo "http://$HOSTNAME:$port" > "$ROOT/$APP/URL"
else
	# Regular deploy
	oldid=$(< "$ROOT/$APP/CONTAINER")
	docker kill $oldid > /dev/null
	port=$(< "$ROOT/$APP/PORT")
	id=$(docker run -d -p ":$port" -e "PORT=$port" -e SLUG_URL=http://$SHELF_HOST/slugs/$APP.tgz flynn/slugrunner start web)
	echo $id > "$ROOT/$APP/CONTAINER"
fi

echo "=====> Application deployed:"
echo "       $(< $ROOT/$APP/URL)"
echo