#!/bin/bash
ROOT=/var/lib/demo/apps
HOSTNAME="$(curl -s icanhazip.com)"
SHELF_HOST="$(/usr/local/bin/sdutil services -1 shelf)"

APP="$2"

mkdir -p $ROOT/$APP

echo "-----> Building $APP ..."
cat | docker run -i -a stdin -a stdout flynn/slugbuilder http://$SHELF_HOST/$APP.tgz

echo "-----> Deploying $APP ..."
if [[ -f "$ROOT/$APP/PORT" ]]; then
	oldid=$(< "$ROOT/$APP/CONTAINER")
	docker kill $oldid > /dev/null
fi
id=$(docker run -d -p 5000 -e PORT=5000 -e SLUG_URL=http://$SHELF_HOST/$APP.tgz flynn/slugrunner start web)
echo $id > "$ROOT/$APP/CONTAINER"
port=$(docker port $id 5000 | sed 's/0.0.0.0://')
echo $port > "$ROOT/$APP/PORT"
echo "http://$HOSTNAME:$port" > "$ROOT/$APP/URL"

echo "=====> Application deployed:"
echo "       $(< $ROOT/$APP/URL)"
echo