source 'https://rubygems.org'

gem 'sprockets', :git => 'https://github.com/rails/sprockets.git', :tag => 'v3.2.0'
gem 'es6-module-mapper', :git => 'https://github.com/jvatic/es6-module-mapper.git', :branch => 'master'
gem 'react-jsx-sprockets', :git => 'https://github.com/jvatic/react-jsx-sprockets', :branch => 'master'
gem 'marbles-js', :git => 'https://github.com/jvatic/marbles-js.git', :branch => 'es6-modules'
gem 'rake'
