// AUTOGENERATED FILE; see /home/vagrant/go/src/github.com/docker/docker/hack/make/.go-autogen
package dockerversion

var (
	GITCOMMIT string = "e589dc7"
	VERSION   string = "1.5.0-dev"

	IAMSTATIC string = "true"
	INITSHA1  string = ""
	INITPATH  string = ""
)
