// Code generated by protoc-gen-go. DO NOT EDIT.
// source: router.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RouteConfig_Version int32

const (
	// Unused/invalid default value.
	RouteConfig_VERSION_UNSPECIFIED RouteConfig_Version = 0
	// VERSION_1 represents route config v1.
	RouteConfig_VERSION_1 RouteConfig_Version = 1
)

var RouteConfig_Version_name = map[int32]string{
	0: "VERSION_UNSPECIFIED",
	1: "VERSION_1",
}

var RouteConfig_Version_value = map[string]int32{
	"VERSION_UNSPECIFIED": 0,
	"VERSION_1":           1,
}

func (x RouteConfig_Version) String() string {
	return proto.EnumName(RouteConfig_Version_name, int32(x))
}

func (RouteConfig_Version) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_367072455c71aedc, []int{4, 0}
}

type RouteChange_Action int32

const (
	// Unused/invalid default value.
	RouteChange_ACTION_UNSPECIFIED RouteChange_Action = 0
	// ACTION_CREATE represents a route that was created.
	RouteChange_ACTION_CREATE RouteChange_Action = 1
	// ACTION_UPDATE represents a route that was updated.
	RouteChange_ACTION_UPDATE RouteChange_Action = 2
	// ACTION_DELETE represents a route that was deleted.
	RouteChange_ACTION_DELETE RouteChange_Action = 3
)

var RouteChange_Action_name = map[int32]string{
	0: "ACTION_UNSPECIFIED",
	1: "ACTION_CREATE",
	2: "ACTION_UPDATE",
	3: "ACTION_DELETE",
}

var RouteChange_Action_value = map[string]int32{
	"ACTION_UNSPECIFIED": 0,
	"ACTION_CREATE":      1,
	"ACTION_UPDATE":      2,
	"ACTION_DELETE":      3,
}

func (x RouteChange_Action) String() string {
	return proto.EnumName(RouteChange_Action_name, int32(x))
}

func (RouteChange_Action) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_367072455c71aedc, []int{6, 0}
}

// SetRoutesRequest is a request to set a list of app routes.
type SetRoutesRequest struct {
	// app_routes are the app routes to set.
	AppRoutes []*AppRoutes `protobuf:"bytes,1,rep,name=app_routes,json=appRoutes,proto3" json:"app_routes,omitempty"`
	// dry_run indicates whether to just generate the changes that would be
	// applied to existing routes by this request (true) or to also atomically
	// apply the route changes (false).
	DryRun bool `protobuf:"varint,2,opt,name=dry_run,json=dryRun,proto3" json:"dry_run,omitempty"`
	// expected_state is the expected state of existing routes to apply this
	// request to, with the request failing if the actual state differs.
	ExpectedState        []byte   `protobuf:"bytes,3,opt,name=expected_state,json=expectedState,proto3" json:"expected_state,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetRoutesRequest) Reset()         { *m = SetRoutesRequest{} }
func (m *SetRoutesRequest) String() string { return proto.CompactTextString(m) }
func (*SetRoutesRequest) ProtoMessage()    {}
func (*SetRoutesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_367072455c71aedc, []int{0}
}

func (m *SetRoutesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetRoutesRequest.Unmarshal(m, b)
}
func (m *SetRoutesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetRoutesRequest.Marshal(b, m, deterministic)
}
func (m *SetRoutesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetRoutesRequest.Merge(m, src)
}
func (m *SetRoutesRequest) XXX_Size() int {
	return xxx_messageInfo_SetRoutesRequest.Size(m)
}
func (m *SetRoutesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetRoutesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetRoutesRequest proto.InternalMessageInfo

func (m *SetRoutesRequest) GetAppRoutes() []*AppRoutes {
	if m != nil {
		return m.AppRoutes
	}
	return nil
}

func (m *SetRoutesRequest) GetDryRun() bool {
	if m != nil {
		return m.DryRun
	}
	return false
}

func (m *SetRoutesRequest) GetExpectedState() []byte {
	if m != nil {
		return m.ExpectedState
	}
	return nil
}

// SetRoutesResponse is a response to a SetRoutes request.
type SetRoutesResponse struct {
	// route_changes is the list of route changes that were either applied if
	// dry_run=false or that would have been applied if dry_run=true.
	RouteChanges []*RouteChange `protobuf:"bytes,1,rep,name=route_changes,json=routeChanges,proto3" json:"route_changes,omitempty"`
	// dry_run indicates whether the request was a dry run or not.
	DryRun bool `protobuf:"varint,2,opt,name=dry_run,json=dryRun,proto3" json:"dry_run,omitempty"`
	// applied_to_state is the state of the existing routes that this request was
	// applied to, and can be used as the expected_state in a subsequent request
	// to confirm the application of a dry run.
	AppliedToState       []byte   `protobuf:"bytes,3,opt,name=applied_to_state,json=appliedToState,proto3" json:"applied_to_state,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetRoutesResponse) Reset()         { *m = SetRoutesResponse{} }
func (m *SetRoutesResponse) String() string { return proto.CompactTextString(m) }
func (*SetRoutesResponse) ProtoMessage()    {}
func (*SetRoutesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_367072455c71aedc, []int{1}
}

func (m *SetRoutesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetRoutesResponse.Unmarshal(m, b)
}
func (m *SetRoutesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetRoutesResponse.Marshal(b, m, deterministic)
}
func (m *SetRoutesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetRoutesResponse.Merge(m, src)
}
func (m *SetRoutesResponse) XXX_Size() int {
	return xxx_messageInfo_SetRoutesResponse.Size(m)
}
func (m *SetRoutesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetRoutesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetRoutesResponse proto.InternalMessageInfo

func (m *SetRoutesResponse) GetRouteChanges() []*RouteChange {
	if m != nil {
		return m.RouteChanges
	}
	return nil
}

func (m *SetRoutesResponse) GetDryRun() bool {
	if m != nil {
		return m.DryRun
	}
	return false
}

func (m *SetRoutesResponse) GetAppliedToState() []byte {
	if m != nil {
		return m.AppliedToState
	}
	return nil
}

// ListAppRoutesRequest is a request to list routes for a set of apps.
type ListAppRoutesRequest struct {
	// apps is the set of apps to list routes for.
	Apps                 []string `protobuf:"bytes,1,rep,name=apps,proto3" json:"apps,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListAppRoutesRequest) Reset()         { *m = ListAppRoutesRequest{} }
func (m *ListAppRoutesRequest) String() string { return proto.CompactTextString(m) }
func (*ListAppRoutesRequest) ProtoMessage()    {}
func (*ListAppRoutesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_367072455c71aedc, []int{2}
}

func (m *ListAppRoutesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAppRoutesRequest.Unmarshal(m, b)
}
func (m *ListAppRoutesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAppRoutesRequest.Marshal(b, m, deterministic)
}
func (m *ListAppRoutesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAppRoutesRequest.Merge(m, src)
}
func (m *ListAppRoutesRequest) XXX_Size() int {
	return xxx_messageInfo_ListAppRoutesRequest.Size(m)
}
func (m *ListAppRoutesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAppRoutesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListAppRoutesRequest proto.InternalMessageInfo

func (m *ListAppRoutesRequest) GetApps() []string {
	if m != nil {
		return m.Apps
	}
	return nil
}

// ListAppRoutesResponse is a response to list routes for a set of apps.
type ListAppRoutesResponse struct {
	// app_routes are the requested routes.
	AppRoutes []*AppRoutes `protobuf:"bytes,1,rep,name=app_routes,json=appRoutes,proto3" json:"app_routes,omitempty"`
	// state is the state of the returned routes that can be used as the
	// expected_state in a subsequent call to SetRoutes.
	State                []byte   `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListAppRoutesResponse) Reset()         { *m = ListAppRoutesResponse{} }
func (m *ListAppRoutesResponse) String() string { return proto.CompactTextString(m) }
func (*ListAppRoutesResponse) ProtoMessage()    {}
func (*ListAppRoutesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_367072455c71aedc, []int{3}
}

func (m *ListAppRoutesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAppRoutesResponse.Unmarshal(m, b)
}
func (m *ListAppRoutesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAppRoutesResponse.Marshal(b, m, deterministic)
}
func (m *ListAppRoutesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAppRoutesResponse.Merge(m, src)
}
func (m *ListAppRoutesResponse) XXX_Size() int {
	return xxx_messageInfo_ListAppRoutesResponse.Size(m)
}
func (m *ListAppRoutesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAppRoutesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListAppRoutesResponse proto.InternalMessageInfo

func (m *ListAppRoutesResponse) GetAppRoutes() []*AppRoutes {
	if m != nil {
		return m.AppRoutes
	}
	return nil
}

func (m *ListAppRoutesResponse) GetState() []byte {
	if m != nil {
		return m.State
	}
	return nil
}

// RouteConfig is used to define routes in route config files.
type RouteConfig struct {
	// version is the version of a route config.
	Version RouteConfig_Version `protobuf:"varint,1,opt,name=version,proto3,enum=flynn.api.v1.RouteConfig_Version" json:"version,omitempty"`
	// app_routes are the app routes that the route config defines.
	AppRoutes            []*AppRoutes `protobuf:"bytes,2,rep,name=app_routes,json=appRoutes,proto3" json:"app_routes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *RouteConfig) Reset()         { *m = RouteConfig{} }
func (m *RouteConfig) String() string { return proto.CompactTextString(m) }
func (*RouteConfig) ProtoMessage()    {}
func (*RouteConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_367072455c71aedc, []int{4}
}

func (m *RouteConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RouteConfig.Unmarshal(m, b)
}
func (m *RouteConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RouteConfig.Marshal(b, m, deterministic)
}
func (m *RouteConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RouteConfig.Merge(m, src)
}
func (m *RouteConfig) XXX_Size() int {
	return xxx_messageInfo_RouteConfig.Size(m)
}
func (m *RouteConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_RouteConfig.DiscardUnknown(m)
}

var xxx_messageInfo_RouteConfig proto.InternalMessageInfo

func (m *RouteConfig) GetVersion() RouteConfig_Version {
	if m != nil {
		return m.Version
	}
	return RouteConfig_VERSION_UNSPECIFIED
}

func (m *RouteConfig) GetAppRoutes() []*AppRoutes {
	if m != nil {
		return m.AppRoutes
	}
	return nil
}

// AppRoutes is a list of desired routes for an app.
type AppRoutes struct {
	// app is an identifier for the app.
	App string `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	// routes are the desired routes for the app.
	Routes               []*Route `protobuf:"bytes,2,rep,name=routes,proto3" json:"routes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppRoutes) Reset()         { *m = AppRoutes{} }
func (m *AppRoutes) String() string { return proto.CompactTextString(m) }
func (*AppRoutes) ProtoMessage()    {}
func (*AppRoutes) Descriptor() ([]byte, []int) {
	return fileDescriptor_367072455c71aedc, []int{5}
}

func (m *AppRoutes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppRoutes.Unmarshal(m, b)
}
func (m *AppRoutes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppRoutes.Marshal(b, m, deterministic)
}
func (m *AppRoutes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppRoutes.Merge(m, src)
}
func (m *AppRoutes) XXX_Size() int {
	return xxx_messageInfo_AppRoutes.Size(m)
}
func (m *AppRoutes) XXX_DiscardUnknown() {
	xxx_messageInfo_AppRoutes.DiscardUnknown(m)
}

var xxx_messageInfo_AppRoutes proto.InternalMessageInfo

func (m *AppRoutes) GetApp() string {
	if m != nil {
		return m.App
	}
	return ""
}

func (m *AppRoutes) GetRoutes() []*Route {
	if m != nil {
		return m.Routes
	}
	return nil
}

// RouteChange is a change made to a route in response to a SetRoutes request.
type RouteChange struct {
	// action is the action that was performed.
	Action RouteChange_Action `protobuf:"varint,1,opt,name=action,proto3,enum=flynn.api.v1.RouteChange_Action" json:"action,omitempty"`
	// before is the route before the action was applied.
	Before *Route `protobuf:"bytes,2,opt,name=before,proto3" json:"before,omitempty"`
	// after is the route after the action was applied.
	After                *Route   `protobuf:"bytes,3,opt,name=after,proto3" json:"after,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RouteChange) Reset()         { *m = RouteChange{} }
func (m *RouteChange) String() string { return proto.CompactTextString(m) }
func (*RouteChange) ProtoMessage()    {}
func (*RouteChange) Descriptor() ([]byte, []int) {
	return fileDescriptor_367072455c71aedc, []int{6}
}

func (m *RouteChange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RouteChange.Unmarshal(m, b)
}
func (m *RouteChange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RouteChange.Marshal(b, m, deterministic)
}
func (m *RouteChange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RouteChange.Merge(m, src)
}
func (m *RouteChange) XXX_Size() int {
	return xxx_messageInfo_RouteChange.Size(m)
}
func (m *RouteChange) XXX_DiscardUnknown() {
	xxx_messageInfo_RouteChange.DiscardUnknown(m)
}

var xxx_messageInfo_RouteChange proto.InternalMessageInfo

func (m *RouteChange) GetAction() RouteChange_Action {
	if m != nil {
		return m.Action
	}
	return RouteChange_ACTION_UNSPECIFIED
}

func (m *RouteChange) GetBefore() *Route {
	if m != nil {
		return m.Before
	}
	return nil
}

func (m *RouteChange) GetAfter() *Route {
	if m != nil {
		return m.After
	}
	return nil
}

// Route is a HTTP or TCP route.
type Route struct {
	// Output only. The unique identifier of this route resource in the format:
	// `apps/{APP_ID}/routes/{ROUTE_ID}`
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Required. The parent resource name, in the format `apps/{APP_ID}` or
	// `apps/{APP_DISPLAY_NAME}`
	Parent string `protobuf:"bytes,2,opt,name=parent,proto3" json:"parent,omitempty"`
	// Required. The discoverd service target for this route.
	ServiceTarget *Route_ServiceTarget `protobuf:"bytes,3,opt,name=service_target,json=serviceTarget,proto3" json:"service_target,omitempty"`
	// Disable keep-alives between the router and backends for this route.
	DisableKeepAlives bool `protobuf:"varint,4,opt,name=disable_keep_alives,json=disableKeepAlives,proto3" json:"disable_keep_alives,omitempty"`
	// The protocol-specific configuration.
	//
	// Types that are valid to be assigned to Config:
	//	*Route_Http
	//	*Route_Tcp
	Config               isRoute_Config `protobuf_oneof:"config"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Route) Reset()         { *m = Route{} }
func (m *Route) String() string { return proto.CompactTextString(m) }
func (*Route) ProtoMessage()    {}
func (*Route) Descriptor() ([]byte, []int) {
	return fileDescriptor_367072455c71aedc, []int{7}
}

func (m *Route) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Route.Unmarshal(m, b)
}
func (m *Route) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Route.Marshal(b, m, deterministic)
}
func (m *Route) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Route.Merge(m, src)
}
func (m *Route) XXX_Size() int {
	return xxx_messageInfo_Route.Size(m)
}
func (m *Route) XXX_DiscardUnknown() {
	xxx_messageInfo_Route.DiscardUnknown(m)
}

var xxx_messageInfo_Route proto.InternalMessageInfo

func (m *Route) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Route) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *Route) GetServiceTarget() *Route_ServiceTarget {
	if m != nil {
		return m.ServiceTarget
	}
	return nil
}

func (m *Route) GetDisableKeepAlives() bool {
	if m != nil {
		return m.DisableKeepAlives
	}
	return false
}

type isRoute_Config interface {
	isRoute_Config()
}

type Route_Http struct {
	Http *Route_HTTP `protobuf:"bytes,5,opt,name=http,proto3,oneof"`
}

type Route_Tcp struct {
	Tcp *Route_TCP `protobuf:"bytes,6,opt,name=tcp,proto3,oneof"`
}

func (*Route_Http) isRoute_Config() {}

func (*Route_Tcp) isRoute_Config() {}

func (m *Route) GetConfig() isRoute_Config {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *Route) GetHttp() *Route_HTTP {
	if x, ok := m.GetConfig().(*Route_Http); ok {
		return x.Http
	}
	return nil
}

func (m *Route) GetTcp() *Route_TCP {
	if x, ok := m.GetConfig().(*Route_Tcp); ok {
		return x.Tcp
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Route) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Route_Http)(nil),
		(*Route_Tcp)(nil),
	}
}

// A discoverd service target.
type Route_ServiceTarget struct {
	// Required. The discoverd service name to route requests to.
	ServiceName string `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	// Route to the service leader.
	Leader bool `protobuf:"varint,2,opt,name=leader,proto3" json:"leader,omitempty"`
	// Wait for in-flight requests to this target to finish before backends are terminated.
	DrainBackends        bool     `protobuf:"varint,3,opt,name=drain_backends,json=drainBackends,proto3" json:"drain_backends,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Route_ServiceTarget) Reset()         { *m = Route_ServiceTarget{} }
func (m *Route_ServiceTarget) String() string { return proto.CompactTextString(m) }
func (*Route_ServiceTarget) ProtoMessage()    {}
func (*Route_ServiceTarget) Descriptor() ([]byte, []int) {
	return fileDescriptor_367072455c71aedc, []int{7, 0}
}

func (m *Route_ServiceTarget) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Route_ServiceTarget.Unmarshal(m, b)
}
func (m *Route_ServiceTarget) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Route_ServiceTarget.Marshal(b, m, deterministic)
}
func (m *Route_ServiceTarget) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Route_ServiceTarget.Merge(m, src)
}
func (m *Route_ServiceTarget) XXX_Size() int {
	return xxx_messageInfo_Route_ServiceTarget.Size(m)
}
func (m *Route_ServiceTarget) XXX_DiscardUnknown() {
	xxx_messageInfo_Route_ServiceTarget.DiscardUnknown(m)
}

var xxx_messageInfo_Route_ServiceTarget proto.InternalMessageInfo

func (m *Route_ServiceTarget) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (m *Route_ServiceTarget) GetLeader() bool {
	if m != nil {
		return m.Leader
	}
	return false
}

func (m *Route_ServiceTarget) GetDrainBackends() bool {
	if m != nil {
		return m.DrainBackends
	}
	return false
}

type Route_HTTP struct {
	// Required. The name of the server that this route matches. May contain up
	// to 10 wildcard labels for plaintext HTTP routes or a single wildcard
	// label for TLS routes, followed by one or more non-wildcard labels. This
	// is matched against SNI to choose the TLS configuration and the Host
	// header to select the route.
	Domain string `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	// The HTTP path prefix to match against. Defaults to the root path `/`. To
	// create a route with a non-root path prefix, a root path route must already
	// exist for the same listener and domain, which will be used for the TLS and
	// HSTS configuration. Trailing slashes are stripped and only full path
	// segments are matched. The full unstripped path is sent in requests to the
	// target.
	Path string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	// Enables best-effort session-backend stickiness using an encrypted cookie set
	// and managed by the router that will send requests containing the cookie to
	// the same backend instance. Incompatible with RedirectTarget.
	StickySessions       *Route_HTTP_StickySessions `protobuf:"bytes,3,opt,name=sticky_sessions,json=stickySessions,proto3" json:"sticky_sessions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *Route_HTTP) Reset()         { *m = Route_HTTP{} }
func (m *Route_HTTP) String() string { return proto.CompactTextString(m) }
func (*Route_HTTP) ProtoMessage()    {}
func (*Route_HTTP) Descriptor() ([]byte, []int) {
	return fileDescriptor_367072455c71aedc, []int{7, 1}
}

func (m *Route_HTTP) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Route_HTTP.Unmarshal(m, b)
}
func (m *Route_HTTP) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Route_HTTP.Marshal(b, m, deterministic)
}
func (m *Route_HTTP) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Route_HTTP.Merge(m, src)
}
func (m *Route_HTTP) XXX_Size() int {
	return xxx_messageInfo_Route_HTTP.Size(m)
}
func (m *Route_HTTP) XXX_DiscardUnknown() {
	xxx_messageInfo_Route_HTTP.DiscardUnknown(m)
}

var xxx_messageInfo_Route_HTTP proto.InternalMessageInfo

func (m *Route_HTTP) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *Route_HTTP) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Route_HTTP) GetStickySessions() *Route_HTTP_StickySessions {
	if m != nil {
		return m.StickySessions
	}
	return nil
}

// Sticky session configuration. Currently there are no configuration options.
type Route_HTTP_StickySessions struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Route_HTTP_StickySessions) Reset()         { *m = Route_HTTP_StickySessions{} }
func (m *Route_HTTP_StickySessions) String() string { return proto.CompactTextString(m) }
func (*Route_HTTP_StickySessions) ProtoMessage()    {}
func (*Route_HTTP_StickySessions) Descriptor() ([]byte, []int) {
	return fileDescriptor_367072455c71aedc, []int{7, 1, 0}
}

func (m *Route_HTTP_StickySessions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Route_HTTP_StickySessions.Unmarshal(m, b)
}
func (m *Route_HTTP_StickySessions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Route_HTTP_StickySessions.Marshal(b, m, deterministic)
}
func (m *Route_HTTP_StickySessions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Route_HTTP_StickySessions.Merge(m, src)
}
func (m *Route_HTTP_StickySessions) XXX_Size() int {
	return xxx_messageInfo_Route_HTTP_StickySessions.Size(m)
}
func (m *Route_HTTP_StickySessions) XXX_DiscardUnknown() {
	xxx_messageInfo_Route_HTTP_StickySessions.DiscardUnknown(m)
}

var xxx_messageInfo_Route_HTTP_StickySessions proto.InternalMessageInfo

type Route_TCP struct {
	// The TCP port configuration for the route. Required and only valid for TCP
	// listeners.
	Port                 *Route_TCPPort `protobuf:"bytes,1,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Route_TCP) Reset()         { *m = Route_TCP{} }
func (m *Route_TCP) String() string { return proto.CompactTextString(m) }
func (*Route_TCP) ProtoMessage()    {}
func (*Route_TCP) Descriptor() ([]byte, []int) {
	return fileDescriptor_367072455c71aedc, []int{7, 2}
}

func (m *Route_TCP) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Route_TCP.Unmarshal(m, b)
}
func (m *Route_TCP) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Route_TCP.Marshal(b, m, deterministic)
}
func (m *Route_TCP) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Route_TCP.Merge(m, src)
}
func (m *Route_TCP) XXX_Size() int {
	return xxx_messageInfo_Route_TCP.Size(m)
}
func (m *Route_TCP) XXX_DiscardUnknown() {
	xxx_messageInfo_Route_TCP.DiscardUnknown(m)
}

var xxx_messageInfo_Route_TCP proto.InternalMessageInfo

func (m *Route_TCP) GetPort() *Route_TCPPort {
	if m != nil {
		return m.Port
	}
	return nil
}

type Route_TCPPort struct {
	// The TCP port to bind to. If unspecified, a port will be automatically chosen
	// during route creation and provided in the response.
	Port                 uint32   `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Route_TCPPort) Reset()         { *m = Route_TCPPort{} }
func (m *Route_TCPPort) String() string { return proto.CompactTextString(m) }
func (*Route_TCPPort) ProtoMessage()    {}
func (*Route_TCPPort) Descriptor() ([]byte, []int) {
	return fileDescriptor_367072455c71aedc, []int{7, 3}
}

func (m *Route_TCPPort) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Route_TCPPort.Unmarshal(m, b)
}
func (m *Route_TCPPort) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Route_TCPPort.Marshal(b, m, deterministic)
}
func (m *Route_TCPPort) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Route_TCPPort.Merge(m, src)
}
func (m *Route_TCPPort) XXX_Size() int {
	return xxx_messageInfo_Route_TCPPort.Size(m)
}
func (m *Route_TCPPort) XXX_DiscardUnknown() {
	xxx_messageInfo_Route_TCPPort.DiscardUnknown(m)
}

var xxx_messageInfo_Route_TCPPort proto.InternalMessageInfo

func (m *Route_TCPPort) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func init() {
	proto.RegisterEnum("flynn.api.v1.RouteConfig_Version", RouteConfig_Version_name, RouteConfig_Version_value)
	proto.RegisterEnum("flynn.api.v1.RouteChange_Action", RouteChange_Action_name, RouteChange_Action_value)
	proto.RegisterType((*SetRoutesRequest)(nil), "flynn.api.v1.SetRoutesRequest")
	proto.RegisterType((*SetRoutesResponse)(nil), "flynn.api.v1.SetRoutesResponse")
	proto.RegisterType((*ListAppRoutesRequest)(nil), "flynn.api.v1.ListAppRoutesRequest")
	proto.RegisterType((*ListAppRoutesResponse)(nil), "flynn.api.v1.ListAppRoutesResponse")
	proto.RegisterType((*RouteConfig)(nil), "flynn.api.v1.RouteConfig")
	proto.RegisterType((*AppRoutes)(nil), "flynn.api.v1.AppRoutes")
	proto.RegisterType((*RouteChange)(nil), "flynn.api.v1.RouteChange")
	proto.RegisterType((*Route)(nil), "flynn.api.v1.Route")
	proto.RegisterType((*Route_ServiceTarget)(nil), "flynn.api.v1.Route.ServiceTarget")
	proto.RegisterType((*Route_HTTP)(nil), "flynn.api.v1.Route.HTTP")
	proto.RegisterType((*Route_HTTP_StickySessions)(nil), "flynn.api.v1.Route.HTTP.StickySessions")
	proto.RegisterType((*Route_TCP)(nil), "flynn.api.v1.Route.TCP")
	proto.RegisterType((*Route_TCPPort)(nil), "flynn.api.v1.Route.TCPPort")
}

func init() { proto.RegisterFile("router.proto", fileDescriptor_367072455c71aedc) }

var fileDescriptor_367072455c71aedc = []byte{
	// 799 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0xd1, 0x6e, 0xe3, 0x44,
	0x14, 0x5d, 0x37, 0x89, 0xdb, 0xdc, 0xc6, 0xc1, 0x9d, 0x2e, 0x1b, 0x13, 0x04, 0x64, 0x8d, 0x10,
	0x81, 0x95, 0x8c, 0x1a, 0xa4, 0x15, 0x12, 0x12, 0x52, 0x9a, 0x1a, 0xb5, 0x50, 0x95, 0x68, 0xe2,
	0x5d, 0x01, 0x2f, 0xd6, 0xc4, 0x9e, 0xb4, 0x56, 0xb3, 0xf6, 0xec, 0xcc, 0x24, 0x22, 0xbf, 0xc0,
	0x07, 0xec, 0x77, 0xf0, 0xc2, 0xb7, 0x21, 0xf1, 0x84, 0x3c, 0x33, 0xc9, 0xc6, 0x25, 0x59, 0x21,
	0xde, 0xe6, 0x9e, 0x39, 0x77, 0xee, 0xb9, 0x67, 0xc6, 0xd7, 0xd0, 0xe2, 0xc5, 0x42, 0x52, 0x1e,
	0x30, 0x5e, 0xc8, 0x02, 0xb5, 0x66, 0xf3, 0x55, 0x9e, 0x07, 0x84, 0x65, 0xc1, 0xf2, 0xcc, 0xff,
	0xdd, 0x02, 0x77, 0x42, 0x25, 0x2e, 0x19, 0x02, 0xd3, 0xd7, 0x0b, 0x2a, 0x24, 0x7a, 0x0e, 0x40,
	0x18, 0x8b, 0x55, 0x9a, 0xf0, 0xac, 0x5e, 0xad, 0x7f, 0x3c, 0xe8, 0x04, 0xdb, 0x79, 0xc1, 0x90,
	0x31, 0x93, 0xd3, 0x24, 0xeb, 0x25, 0xea, 0xc0, 0x61, 0xca, 0x57, 0x31, 0x5f, 0xe4, 0xde, 0x41,
	0xcf, 0xea, 0x1f, 0x61, 0x3b, 0xe5, 0x2b, 0xbc, 0xc8, 0xd1, 0x67, 0xd0, 0xa6, 0xbf, 0x31, 0x9a,
	0x48, 0x9a, 0xc6, 0x42, 0x12, 0x49, 0xbd, 0x5a, 0xcf, 0xea, 0xb7, 0xb0, 0xb3, 0x46, 0x27, 0x25,
	0xe8, 0xbf, 0xb1, 0xe0, 0x64, 0x4b, 0x8c, 0x60, 0x45, 0x2e, 0x28, 0xfa, 0x0e, 0x1c, 0xa5, 0x24,
	0x4e, 0xee, 0x48, 0x7e, 0xbb, 0x11, 0xf4, 0x41, 0x55, 0x90, 0x4a, 0x1a, 0x29, 0x06, 0xd6, 0x0d,
	0xeb, 0xe0, 0x1d, 0xaa, 0xfa, 0xe0, 0x12, 0xc6, 0xe6, 0x19, 0x4d, 0x63, 0x59, 0x54, 0x74, 0xb5,
	0x0d, 0x1e, 0x15, 0x5a, 0xd8, 0x97, 0xf0, 0xf8, 0x3a, 0x13, 0xf2, 0x6d, 0xd3, 0xc6, 0x28, 0x04,
	0x75, 0xc2, 0x98, 0x56, 0xd4, 0xc4, 0x6a, 0xed, 0x53, 0x78, 0xff, 0x01, 0xd7, 0xf4, 0xf1, 0x7f,
	0x5d, 0x7d, 0x0c, 0x0d, 0xad, 0xed, 0x40, 0x69, 0xd3, 0x81, 0xff, 0xa7, 0x05, 0xc7, 0xba, 0xe7,
	0x22, 0x9f, 0x65, 0xb7, 0xe8, 0x5b, 0x38, 0x5c, 0x52, 0x2e, 0xb2, 0x22, 0xf7, 0xac, 0x9e, 0xd5,
	0x6f, 0x0f, 0x9e, 0xee, 0xf2, 0x47, 0x71, 0x83, 0x97, 0x9a, 0x88, 0xd7, 0x19, 0x0f, 0xa4, 0x1d,
	0xfc, 0x57, 0x69, 0xfe, 0x19, 0x1c, 0x9a, 0xb3, 0x50, 0x07, 0x4e, 0x5f, 0x86, 0x78, 0x72, 0xf5,
	0xd3, 0x4d, 0xfc, 0xe2, 0x66, 0x32, 0x0e, 0x47, 0x57, 0xdf, 0x5f, 0x85, 0x17, 0xee, 0x23, 0xe4,
	0x40, 0x73, 0xbd, 0x71, 0xe6, 0x5a, 0xfe, 0x0f, 0xd0, 0xdc, 0x1c, 0x85, 0x5c, 0xa8, 0x11, 0xc6,
	0x94, 0xe0, 0x26, 0x2e, 0x97, 0xe8, 0x19, 0xd8, 0x15, 0x15, 0xa7, 0x3b, 0xba, 0xc0, 0x86, 0xe2,
	0xff, 0xbd, 0xf1, 0x40, 0x5d, 0x35, 0xfa, 0x06, 0x6c, 0x92, 0xc8, 0xb7, 0x16, 0xf4, 0xf6, 0x3e,
	0x91, 0x60, 0xa8, 0x78, 0xd8, 0xf0, 0xcb, 0xb2, 0x53, 0x3a, 0x2b, 0xb8, 0x36, 0x79, 0x5f, 0x59,
	0x4d, 0x41, 0x5f, 0x40, 0x83, 0xcc, 0x24, 0xe5, 0xea, 0xb1, 0xec, 0xe1, 0x6a, 0x86, 0xff, 0x0b,
	0xd8, 0xba, 0x12, 0x7a, 0x02, 0x68, 0x38, 0x8a, 0xfe, 0x6d, 0xcf, 0x09, 0x38, 0x06, 0x1f, 0xe1,
	0x70, 0x18, 0x85, 0xae, 0xb5, 0x05, 0xbd, 0x18, 0x5f, 0x94, 0xd0, 0xc1, 0x16, 0x74, 0x11, 0x5e,
	0x87, 0x51, 0xe8, 0xd6, 0xfc, 0xbf, 0xea, 0xd0, 0x50, 0xb5, 0xca, 0x57, 0x98, 0x93, 0x57, 0xd4,
	0xd8, 0xa8, 0xd6, 0xe8, 0x09, 0xd8, 0x8c, 0x70, 0x9a, 0x4b, 0xd5, 0x50, 0x13, 0x9b, 0x08, 0x5d,
	0x42, 0x5b, 0x50, 0xbe, 0xcc, 0x12, 0x1a, 0x4b, 0xc2, 0x6f, 0xa9, 0x34, 0x4d, 0xec, 0x7a, 0x2d,
	0xc1, 0x44, 0x33, 0x23, 0x45, 0xc4, 0x8e, 0xd8, 0x0e, 0x51, 0x00, 0xa7, 0x69, 0x26, 0xc8, 0x74,
	0x4e, 0xe3, 0x7b, 0x4a, 0x59, 0x4c, 0xe6, 0xd9, 0x92, 0x0a, 0xaf, 0xae, 0x3e, 0xb1, 0x13, 0xb3,
	0xf5, 0x23, 0xa5, 0x6c, 0xa8, 0x36, 0x50, 0x00, 0xf5, 0x3b, 0x29, 0x99, 0xd7, 0x50, 0xf5, 0xbc,
	0x5d, 0xf5, 0x2e, 0xa3, 0x68, 0x7c, 0xf9, 0x08, 0x2b, 0x1e, 0x7a, 0x06, 0x35, 0x99, 0x30, 0xcf,
	0x56, 0xf4, 0xce, 0x2e, 0x7a, 0x34, 0x2a, 0xd9, 0x25, 0xab, 0xfb, 0x1a, 0x9c, 0x8a, 0x58, 0xf4,
	0x14, 0x5a, 0xeb, 0x3e, 0xb7, 0xbc, 0x39, 0x36, 0xd8, 0x8d, 0xb1, 0x68, 0x4e, 0x49, 0x4a, 0xf9,
	0x7a, 0x2c, 0xe8, 0xa8, 0x1c, 0x56, 0x29, 0x27, 0x59, 0x1e, 0x4f, 0x49, 0x72, 0x4f, 0xf3, 0x54,
	0x28, 0x8b, 0x8e, 0xb0, 0xa3, 0xd0, 0x73, 0x03, 0x76, 0xdf, 0x58, 0x50, 0x2f, 0x05, 0x97, 0xe7,
	0xa4, 0xc5, 0x2b, 0x92, 0xe5, 0xa6, 0x88, 0x89, 0xca, 0x6b, 0x61, 0x44, 0xde, 0x99, 0x0b, 0x50,
	0x6b, 0x34, 0x86, 0xf7, 0x84, 0xcc, 0x92, 0xfb, 0x55, 0x2c, 0xa8, 0x28, 0xbf, 0x1b, 0x61, 0xfc,
	0xff, 0x7c, 0x9f, 0x1f, 0xc1, 0x44, 0xf1, 0x27, 0x86, 0x8e, 0xdb, 0xa2, 0x12, 0x77, 0x5d, 0x68,
	0x57, 0x19, 0xdd, 0xe7, 0x50, 0x8b, 0x46, 0x63, 0xf4, 0x15, 0xd4, 0x59, 0xc1, 0xa5, 0x12, 0x75,
	0x3c, 0xf8, 0x70, 0x8f, 0x81, 0xe3, 0x82, 0x4b, 0xac, 0x88, 0xdd, 0x8f, 0xe0, 0xd0, 0x00, 0x4a,
	0xfa, 0x3a, 0xd7, 0xd1, 0xdb, 0xe7, 0x47, 0x60, 0x27, 0x6a, 0x7c, 0x0c, 0xfe, 0xb0, 0xc0, 0x56,
	0x07, 0x70, 0x74, 0x0d, 0xcd, 0xcd, 0xc0, 0x46, 0x1f, 0x57, 0x6b, 0x3c, 0xfc, 0xad, 0x74, 0x3f,
	0xd9, 0xbb, 0x6f, 0x26, 0xe4, 0xcf, 0xe0, 0x54, 0x46, 0x27, 0xf2, 0xab, 0x19, 0xbb, 0x66, 0x70,
	0xf7, 0xd3, 0x77, 0x72, 0xf4, 0xc9, 0xe7, 0x8d, 0x5f, 0x6b, 0x84, 0x65, 0x53, 0x5b, 0xfd, 0x02,
	0xbf, 0xfe, 0x27, 0x00, 0x00, 0xff, 0xff, 0x4e, 0x1c, 0xb6, 0xd8, 0x12, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RouterClient is the client API for Router service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RouterClient interface {
	// SetRoutes takes a desired list of routes for a set of apps, calculates the
	// changes that are needed to the existing routes to realise that list, and
	// then either atomically applies those changes or returns them for user
	// confirmation (otherwise known as a dry run).
	//
	// The given list of routes for each app is expected to contain the desired
	// configuration for all of the app's routes, and so if any existing routes
	// are not contained in the list, or they match ones in the list but have
	// different configuration, then they will be either deleted or updated.
	SetRoutes(ctx context.Context, in *SetRoutesRequest, opts ...grpc.CallOption) (*SetRoutesResponse, error)
	// ListAppRoutes list routes for a set of apps.
	ListAppRoutes(ctx context.Context, in *ListAppRoutesRequest, opts ...grpc.CallOption) (*ListAppRoutesResponse, error)
}

type routerClient struct {
	cc *grpc.ClientConn
}

func NewRouterClient(cc *grpc.ClientConn) RouterClient {
	return &routerClient{cc}
}

func (c *routerClient) SetRoutes(ctx context.Context, in *SetRoutesRequest, opts ...grpc.CallOption) (*SetRoutesResponse, error) {
	out := new(SetRoutesResponse)
	err := c.cc.Invoke(ctx, "/flynn.api.v1.Router/SetRoutes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerClient) ListAppRoutes(ctx context.Context, in *ListAppRoutesRequest, opts ...grpc.CallOption) (*ListAppRoutesResponse, error) {
	out := new(ListAppRoutesResponse)
	err := c.cc.Invoke(ctx, "/flynn.api.v1.Router/ListAppRoutes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RouterServer is the server API for Router service.
type RouterServer interface {
	// SetRoutes takes a desired list of routes for a set of apps, calculates the
	// changes that are needed to the existing routes to realise that list, and
	// then either atomically applies those changes or returns them for user
	// confirmation (otherwise known as a dry run).
	//
	// The given list of routes for each app is expected to contain the desired
	// configuration for all of the app's routes, and so if any existing routes
	// are not contained in the list, or they match ones in the list but have
	// different configuration, then they will be either deleted or updated.
	SetRoutes(context.Context, *SetRoutesRequest) (*SetRoutesResponse, error)
	// ListAppRoutes list routes for a set of apps.
	ListAppRoutes(context.Context, *ListAppRoutesRequest) (*ListAppRoutesResponse, error)
}

// UnimplementedRouterServer can be embedded to have forward compatible implementations.
type UnimplementedRouterServer struct {
}

func (*UnimplementedRouterServer) SetRoutes(ctx context.Context, req *SetRoutesRequest) (*SetRoutesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetRoutes not implemented")
}
func (*UnimplementedRouterServer) ListAppRoutes(ctx context.Context, req *ListAppRoutesRequest) (*ListAppRoutesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAppRoutes not implemented")
}

func RegisterRouterServer(s *grpc.Server, srv RouterServer) {
	s.RegisterService(&_Router_serviceDesc, srv)
}

func _Router_SetRoutes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRoutesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServer).SetRoutes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/flynn.api.v1.Router/SetRoutes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServer).SetRoutes(ctx, req.(*SetRoutesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Router_ListAppRoutes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAppRoutesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServer).ListAppRoutes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/flynn.api.v1.Router/ListAppRoutes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServer).ListAppRoutes(ctx, req.(*ListAppRoutesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Router_serviceDesc = grpc.ServiceDesc{
	ServiceName: "flynn.api.v1.Router",
	HandlerType: (*RouterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetRoutes",
			Handler:    _Router_SetRoutes_Handler,
		},
		{
			MethodName: "ListAppRoutes",
			Handler:    _Router_ListAppRoutes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "router.proto",
}
