FROM flynn/busybox:trusty-20160217

ADD bin/echoer /bin/echoer
ADD bin/ping /bin/pingserv
ADD bin/signal /bin/signal
ADD bin/ish /bin/ish
ADD bin/partial-logger /bin/partial-logger
ADD bin/http-blocker /bin/http-blocker
ADD bin/oom /bin/oom
ADD bin/proxy /bin/proxy
ADD bin/minio /bin/minio
