{
 "title": "Host",
 "description": "Host Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "host_id", "query": "label_values(host_id)" }
  ]
 },
 "panels": [
  { "title": "Host: ${host_id}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "host_id" },
  {
   "title": "Current Memory Used",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(host_memory_total_bytes{host_id=\"${host_id}\"} - host_memory_avail_bytes{host_id=\"${host_id}\"}) / host_memory_total_bytes{host_id=\"${host_id}\"} * 100"
    }
   ]
  },
  {
   "title": "Running Jobs",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "host_jobs_running_total{host_id=\"${host_id}\"}"
    }
   ]
  },
  {
   "title": "Current 1m Load",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "host_load_1m{host_id=\"${host_id}\"}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "host_memory_total_bytes{host_id=\"${host_id}\"} - host_memory_avail_bytes{host_id=\"${host_id}\"}",
     "legendFormat": "used"
    },
    {
     "expr": "host_memory_total_bytes{host_id=\"${host_id}\"}",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Jobs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "host_jobs_running_total{host_id=\"${host_id}\"}",
     "legendFormat": "running"
    },
    {
     "expr": "host_jobs_starting_total{host_id=\"${host_id}\"}",
     "legendFormat": "starting"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "host_load_1m{host_id=\"${host_id}\"}",
     "legendFormat": "load 1m"
    },
    {
     "expr": "host_load_5m{host_id=\"${host_id}\"}",
     "legendFormat": "load 5m"
    },
    {
     "expr": "host_load_15m{host_id=\"${host_id}\"}",
     "legendFormat": "load 15m"
    }
   ]
  }
 ]
}