#!/bin/bash

set -e

usage() {
  cat <<USAGE >&2
usage: $0 [options]

OPTIONS:
  -h            Show this message
  -b BACKEND    The job backend to use (either docker or libvirt-lxc) [default: libvirt-lxc]
  -i IP         The external IP address to bind to [default: the IP assigned to eth0]
USAGE
}


main() {
  local backend ip

  while getopts "hb:i:" opt; do
    case $opt in
      h)
	usage
	exit 1
	;;
      b)
	backend=$OPTARG
	;;
      i)
	ip=$OPTARG
	;;
      ?)
	usage
	exit 1
	;;
    esac
  done

  backend=${backend:-libvirt-lxc}
  ip=${ip:-$(/sbin/ifconfig eth0 | grep 'inet addr:' | cut -d: -f2 | awk '{ print $1}')}

  case "${backend}" in
    libvirt-lxc)
      boot_libvirt_lxc $ip
      ;;
    docker)
      boot_docker $ip
      ;;
    *)
      usage
      exit 1
      ;;
  esac
}

info() {
  local msg=$1
  echo "==> $msg"
}

boot_libvirt_lxc() {
  local ip=$1
  local root="$(cd "$(dirname "$0")/.." && pwd)"
  local host_dir="${root}/host"
  local bootstrap_dir="${root}/bootstrap"

  info "Killing running flynn-host, if any"
  sudo start-stop-daemon \
    --stop \
    --oknodo \
    --retry 15 \
    --exec "${host_dir}/bin/flynn-host"

  local log="/tmp/flynn-host-$(date +%Y-%m-%dT%H-%M-%S.%N).log"
  ln -nfs $log /tmp/flynn-host.log
  info "Starting flynn-host (logging to $log)"
  sudo start-stop-daemon \
    --start \
    --background \
    --no-close \
    --exec "${host_dir}/bin/flynn-host" \
    -- \
    daemon \
    --manifest "${host_dir}/bin/manifest.json" \
    --external $ip \
    --force \
    --backend libvirt-lxc \
    --state /tmp/flynn-host-state.json \
    --flynn-init "${host_dir}/bin/flynn-init" \
    &>$log

  info "Bootstrapping Flynn"
  export DISCOVERD="${ip}:1111"
  export CONTROLLER_DOMAIN="dev.localflynn.com"
  export DEFAULT_ROUTE_DOMAIN="$CONTROLLER_DOMAIN"
  "${bootstrap_dir}/bin/flynn-bootstrap" "${bootstrap_dir}/bin/manifest.json"
}

boot_docker() {
  local ip=$1

  info "Killing running flynn-host, if any"
  local host=$(docker ps | grep flynn-host | cut -d" " -f 1)
  if [ -n "$host" ]; then
    docker stop $host >/dev/null
  fi

  info "Starting flynn-host"
  docker run \
    --detach \
    --volume /var/run/docker.sock:/var/run/docker.sock \
    --publish 1113:1113 \
    flynn/host \
    --external $ip \
    --force \
    --backend docker

  info "Bootstrapping Flynn"
  docker run --env DISCOVERD=$ip:1111 flynn/bootstrap
}

main $@
