#!/bin/bash

set -e

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
source "${ROOT}/script/lib/ui.sh"

usage() {
  cat <<USAGE >&2
usage: $0 [options]

OPTIONS:
  -h            Show this message
  -b BACKEND    The job backend to use (either docker or libvirt-lxc) [default: libvirt-lxc]
  -i IP         The external IP address to bind to [default: the IP assigned to eth0]
USAGE
}

main() {
  local backend ip

  while getopts "hb:i:" opt; do
    case $opt in
      h)
	usage
	exit 1
	;;
      b)
	backend=$OPTARG
	;;
      i)
	ip=$OPTARG
	;;
      ?)
	usage
	exit 1
	;;
    esac
  done

  backend=${backend:-"libvirt-lxc"}
  ip=${ip:-$(/sbin/ifconfig eth0 | grep 'inet addr:' | cut -d: -f2 | awk '{ print $1}')}

  export DISCOVERD="${ip}:1111"
  export CONTROLLER_DOMAIN="dev.localflynn.com"
  export DEFAULT_ROUTE_DOMAIN="${CONTROLLER_DOMAIN}"

  case "${backend}" in
    libvirt-lxc)
      boot_libvirt_lxc $ip
      ;;
    docker)
      boot_docker $ip
      ;;
    *)
      usage
      exit 1
      ;;
  esac
}

boot_libvirt_lxc() {
  local ip=$1
  local host_dir="${ROOT}/host"
  local bootstrap_dir="${ROOT}/bootstrap"

  info "killing running flynn-host, if any"
  sudo start-stop-daemon \
    --stop \
    --oknodo \
    --retry 15 \
    --exec "${host_dir}/bin/flynn-host"

  local log="/tmp/flynn-host-$(date +%Y-%m-%dT%H-%M-%S.%N).log"
  ln -nfs $log /tmp/flynn-host.log
  info "starting flynn-host (logging to $log)"
  sudo start-stop-daemon \
    --start \
    --background \
    --no-close \
    --exec "${host_dir}/bin/flynn-host" \
    -- \
    daemon \
    --manifest "${host_dir}/bin/manifest.json" \
    --external $ip \
    --force \
    --backend libvirt-lxc \
    --state /tmp/flynn-host-state.json \
    --flynn-init "${host_dir}/bin/flynn-init" \
    &>$log

  info "bootstrapping Flynn"
  "${bootstrap_dir}/bin/flynn-bootstrap" "${bootstrap_dir}/bin/manifest.json"
}

boot_docker() {
  local ip=$1

  info "killing running flynn-host, if any"
  local host=$(docker ps | grep flynn-host | cut -d" " -f 1)
  if [ -n "$host" ]; then
    docker stop $host >/dev/null
  fi

  info "starting flynn-host"
  docker run \
    --detach \
    --volume /var/run/docker.sock:/var/run/docker.sock \
    --publish 1113:1113 \
    flynn/host \
    --external $ip \
    --force \
    --backend docker

  info "bootstrapping Flynn"
  docker run \
    --env DISCOVERD="${DISCOVERD}" \
    --env CONTROLLER_DOMAIN="${CONTROLLER_DOMAIN}" \
    --env DEFAULT_ROUTE_DOMAIN="${DEFAULT_ROUTE_DOMAIN}" \
    flynn/bootstrap
}

main $@
