#!/bin/bash
set -eo pipefail

ROOT=$(cd $(dirname "$0")/..; pwd)
cd "$ROOT"

rev=$(git rev-parse HEAD)
version=0-${rev:0:8}
if [[ -n "$(git status --porcelain)" ]]; then
  version+="+"
fi

fpm -s dir -t deb \
  --name flynn-host \
  --version $version \
  --depends aufs-tools \
  --depends libvirt-bin \
  --depends iptables \
  --config-files /etc/flynn/host-manifest.json \
  --config-files /etc/flynn/bootstrap-manifest.json \
  --config-files /etc/flynn/version.json \
  --config-files /etc/init/flynn-host.conf \
  pinkerton/pinkerton=/usr/bin/ \
  bootstrap/bin/flynn-bootstrap=/usr/bin/ \
  host/bin/flynn-host=/usr/bin/ \
  host/bin/flynn-init=/usr/bin/ \
  util/release/flynn-release=/usr/bin/ \
  cli/flynn-cli=/usr/bin/flynn \
  host/bin/manifest.json=/etc/flynn/host-manifest.json \
  bootstrap/bin/manifest.json=/etc/flynn/bootstrap-manifest.json \
  version.json=/etc/flynn/version.json \
  host/upstart.conf=/etc/init/flynn-host.conf
