#!/bin/bash

set -eo pipefail

usage() {
  cat <<USAGE >&2
usage: $0 [options] VERSION

OPTIONS:
  -h            Show this message
  -d DIR        The directory containing the built flynn files [default: the repo this script is in]
USAGE
}

main() {
  local dir

  while getopts "hd:" opt; do
    case $opt in
      h)
        usage
        exit 1
        ;;
      d) dir=${OPTARG} ;;
      ?)
        usage
        exit 1
        ;;
    esac
  done
  shift $((${OPTIND} - 1))

  if [[ $# -ne 1 ]]; then
    usage
    exit 1
  fi

  local version=$1
  dir=${dir:-$(cd $(dirname "$0")/..; pwd)}

  cd "${dir}"
  local rev=$(git rev-parse HEAD)
  local deb_version="0:${version}~${rev:0:8}"

  fpm -s dir -t deb \
    --name flynn-host \
    --version "${deb_version}" \
    --depends aufs-tools \
    --depends libvirt-bin \
    --depends iptables \
    --config-files /etc/flynn/host-manifest.json \
    --config-files /etc/flynn/bootstrap-manifest.json \
    --config-files /etc/flynn/images.json \
    --config-files /etc/init/flynn-host.conf \
    host/bin/flynn-host=/usr/bin/ \
    host/bin/flynn-init=/usr/bin/ \
    cli/flynn-cli=/usr/bin/flynn \
    host/bin/manifest.json=/etc/flynn/host-manifest.json \
    bootstrap/bin/manifest.json=/etc/flynn/bootstrap-manifest.json \
    images.json=/etc/flynn/images.json \
    host/upstart.conf=/etc/init/flynn-host.conf
}

main $@
