#!/bin/bash

set -eo pipefail

usage() {
  cat <<USAGE >&2
usage: $0 [options]

OPTIONS:
  -h            Show this message
  -d DIR        The directory containing the built flynn files [default: the repo this script is in]
  -i ITERATION  The iteration of this release [default: 0]
USAGE
}

main() {
  local dir iteration

  while getopts "hd:i:" opt; do
    case $opt in
      h)
	usage
	exit 1
	;;
      d)
	dir=$OPTARG
	;;
      i)
	iteration=$OPTARG
	;;
      ?)
	usage
	exit 1
	;;
    esac
  done

  dir=${dir:-$(cd $(dirname "$0")/..; pwd)}
  iteration=${iteration:-0}

  cd "${dir}"
  local rev=$(git rev-parse HEAD)
  local version="0:$(date +%Y%m%d).${iteration}~${rev:0:8}"

  fpm -s dir -t deb \
    --name flynn-host \
    --version "${version}" \
    --depends aufs-tools \
    --depends libvirt-bin \
    --depends iptables \
    --config-files /etc/flynn/host-manifest.json \
    --config-files /etc/flynn/bootstrap-manifest.json \
    --config-files /etc/flynn/version.json \
    --config-files /etc/init/flynn-host.conf \
    pinkerton/pinkerton=/usr/bin/ \
    bootstrap/bin/flynn-bootstrap=/usr/bin/ \
    host/bin/flynn-host=/usr/bin/ \
    host/bin/flynn-init=/usr/bin/ \
    util/release/flynn-release=/usr/bin/ \
    cli/flynn-cli=/usr/bin/flynn \
    host/bin/manifest.json=/etc/flynn/host-manifest.json \
    bootstrap/bin/manifest.json=/etc/flynn/bootstrap-manifest.json \
    version.json=/etc/flynn/version.json \
    host/upstart.conf=/etc/init/flynn-host.conf
}

main $@
