#!/bin/bash

set -e

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
source "${ROOT}/script/lib/ui.sh"

usage() {
  cat <<USAGE >&2
usage: $0 [options]

OPTIONS:
  -h            Show this message
  -b BACKEND    The job backend to use [default: `libvirt-lxc`]
USAGE
}

main() {
  local backend

  while getopts "hb:" opt; do
    case $opt in
      h)
        usage
        exit 1
        ;;
      b) backend=${OPTARG} ;;
      ?)
        usage
        exit 1
        ;;
    esac
  done
  shift $((${OPTIND} - 1))

  if [[ $# -ne 0 ]]; then
    usage
    exit 1
  fi

  backend=${backend:-"libvirt-lxc"}

  case "${backend}" in
    libvirt-lxc)
      kill_libvirt_lxc
      ;;
    *)
      usage
      exit 1
      ;;
  esac
}

kill_libvirt_lxc() {
  local flynn_host="${ROOT}/host/bin/flynn-host"

  info "killing running libvirt-lxc flynn-host, if any"
  sudo start-stop-daemon \
    --stop \
    --oknodo \
    --retry 15 \
    --exec "${flynn_host}"

  info "done!"
}

main $@
