#!/bin/bash

set -e

ROOT="$(cd "$(dirname "$0")/.." && pwd)"

main() {
  local test_to_run=$1
  local flynn="${ROOT}/cli/flynn-cli"

  pushd "${ROOT}" >/dev/null
  tup
  popd >/dev/null

  cluster_add=$("${ROOT}/script/bootstrap-flynn" &> >(tee /dev/stderr) | tail -1)

  if [ "${cluster_add:0:17}" != 'flynn cluster add' ]; then
    echo Bootstrap failed >&2
    exit 1
  fi

  export FLYNNRC=/tmp/flynnrc
  "${flynn}" cluster remove default
  "${flynn}" ${cluster_add:6}

  cd "${ROOT}/test"

  test_args="--flynnrc ${FLYNNRC} --cli \"${flynn}\" --debug"
  if [ -n "${test_to_run}" ]; then
    test_args="${test_args} --run ${test_to_run}"
  fi

  bin/flynn-test $test_args
}

main $1
