# -*- mode: ruby -*-
# vi: set ft=ruby :

# Fail if Vagrant version is too old
begin
  Vagrant.require_version ">= 1.6.0"
rescue NoMethodError
  $stderr.puts "This Vagrantfile requires Vagrant version >= 1.6.0"
  exit 1
end

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "flynn-base"
  config.vm.box_url = "https://dl.flynn.io/vagrant/flynn-base.json"
  config.vm.box_version = "> 0"

  config.vm.network "private_network", ip: "192.168.84.42"
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provision "shell", privileged: false, inline: <<SCRIPT
    sudo apt-get update -qq
    sudo apt-get install -y flynn-host
    sudo flynn-release download /etc/flynn/version.json
    sudo start flynn-host

    CONTROLLER_DOMAIN=demo.localflynn.com \
    DEFAULT_ROUTE_DOMAIN=demo.localflynn.com \
    flynn-bootstrap /etc/flynn/bootstrap-manifest.json 2>&1
SCRIPT
end
