source 'https://rubygems.org'

gem 'middleman', '~>3.1.3'
gem 'middleman-more'
gem 'middleman-blog'

gem 'prmd', git: 'git://github.com/IceDragon200/prmd.git', branch: 'for-flynn',
            ref: 'ef8552d99999270755e459eda89f1c4c1e2fd66f'

gem 'builder'
gem 'rake'

gem 'redcarpet'
gem 'pygments.rb'
gem 'activesupport'

gem 'fly', git: 'git://github.com/cupcake/fly.git', branch: 'flynn'
gem 'cupcake-icons', git: 'git://github.com/cupcake/cupcake-icons.git', branch: 'master'

gem 'marbles-js', git: 'git://github.com/jvatic/marbles-js.git',
                  ref: '951e432c3e9bec28d5f42787f9e5b5f760972d1e'
gem 'react-jsx-sprockets', git: 'git://github.com/jvatic/react-jsx-sprockets.git', branch: 'master'

group :development do
  # Live-reloading plugin
  gem 'middleman-livereload', '~> 3.1.0'
  gem 'unicorn'
end
