source 'https://rubygems.org'

gem "middleman"
gem "middleman-more"
gem "middleman-blog"
gem "middleman-sitemap"

gem "builder"
gem "rake"

gem 'redcarpet'
gem 'pygments.rb'
gem 'activesupport'

gem 'fly', :git => 'git://github.com/cupcake/fly.git', :branch => 'flynn'
gem "cupcake-icons", :git => "git://github.com/cupcake/cupcake-icons.git", :branch => "master"

gem 'marbles-js', :git => 'git://github.com/jvatic/marbles-js.git', :ref => 'e11f4b306d0bddac25a768fcee1a3092bfa12700'
gem 'react-jsx-sprockets', :git => 'git://github.com/jvatic/react-jsx-sprockets.git', :branch => 'master'

group :development do
  # Live-reloading plugin
  gem "middleman-livereload"
  gem "unicorn"
end
