require 'fileutils'
require 'erubis'

task compile: [:cli, :copy_contributing] do
  sh 'bundle exec middleman build --no-clean'
end

task :cli do
  require 'yajl'
  require_relative 'lib/cli_doc_compiler'

  json = Yajl::Parser.parse(File.read('cli.json'))
  template = Tilt::ERBTemplate.new('lib/cli.md.erb')

  File.open('source/docs/cli.html.md', 'w') do |f|
    f.write template.render(Processor, docs: json)
  end
end

task :copy_contributing do
  source = <<EOF
---
title: Contributing
layout: docs
---
EOF
  source << File.read('../CONTRIBUTING.md')
  File.write('source/docs/contributing.html.md', source)
end

task :schema do
  FileUtils::Verbose.rm_rf(['schema/controller.json',
                            'schema/controller.md'])

  sh %Q(bundle exec prmd combine -m "schema/meta.json" "schema/schemata/controller" > "schema/controller.json")
  sh %Q(bundle exec prmd verify "schema/controller.json" > /dev/null)
  sh %Q(bundle exec prmd doc "schema/controller.json" > "schema/controller.md")

  renderer = Erubis::Eruby.new(File.read('schema/template.md.erb'))
  File.open('source/docs/controller.html.md', 'w') do |f|
    content = File.read('schema/controller.md')
    # pygments defaults to json, and strangely, doesn't have an alias for it
    content.gsub!('```json', '```')
    f.write(renderer.result(content: content))
  end
end
